#!/bin/sh
# SPDX-License-Identifier: zlib-acknowledgement 

test ! -d build && mkdir build

intel_vtune="$HOME/intel/oneapi/vtune/2021.6.0/sdk"
intel_vtune_flags="-I ${intel_vtune}/include -L ${intel_vtune}/lib64"

common_flags='-fno-exceptions -fno-rtti -std=c++2a'
# IMPORTANT(Ryan): We disable preprocessor warnings to suppress RLIMIT_NOFILE redefinition
# when including <sys/resource.h>
dev_flags="-g -Wall -DHHF_SLOW -DHHF_INTERNAL -Wno-unused-variable -Wp,-w"
# IMPORTANT(Ryan): gcc extension to allow VLA.
# Without, have to use alloca()

libraries="-lX11 -lXrender -lXrandr -lXfixes -lXpresent -ludev -lpulse-simple -lpulse"

g++ $common_flags $dev_flags \
  code/ubuntu-hhf.cpp -o build/ubuntu-hhf \
  $libraries
